ivtv-objs    := ivtv-driver.o ivtv-buf.o ivtv-fileops.o ivtv-i2c.o ivtv-streams.o \
		ivtv-firmware.o ivtv-queue.o ivtv-reset.o \
		ivtv-irq.o ivtv-mailbox.o ivtv-vbi.o \
		ivtv-audio.o ivtv-ioctl.o ivtv-controls.o ivtv-video.o \
		ivtv-cards.o v4l1-compat.o

NO_DECODER_MODULES := $(shell test $(SUBLEVEL) -ge 15 -a $(PATCHLEVEL) -ge 6 -a "$(CONFIG_VIDEO_DECODER)" -a "$(CONFIG_VIDEO_AUDIO_DECODER)" && echo 1)

ifneq ($(NO_DECODER_MODULES),1)
obj-m += wm8775.o
endif

# Use our cx25840 since it provides the NTSC sliced VBI support.
cx25840-objs := cx25840-core.o cx25840-audio.o cx25840-firmware.o cx25840-vbi.o
obj-m += cx25840.o

NO_TUNER_MODULES := $(shell test $(SUBLEVEL) -ge 16 -a $(PATCHLEVEL) -ge 6 -a "$(CONFIG_VIDEO_TUNER)" && echo 1)

ifneq ($(NO_TUNER_MODULES),1)
ifndef NO_IVTV_TUNER
obj-m += tuner.o tveeprom.o tda9887.o
endif
endif

obj-m += ivtv.o

